dist: xenial

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y -qq vim

before_script:
    - git clone https://github.com/junegunn/vader.vim.git

script:
    - vim -Nu tests/tests.vimrc -c 'Vader! tests/*.vader' > /dev/null
